
version: '3'

services: 
    client:
        build: ./client
        volumes:
            - ./client:/app
        ports:
            - 8080:8080
        depends_on: 
            - server
        restart: always
    server: 
        build: ./server
        volumes: 
            - ./client:/app
        ports:
            - 5000:5000 
        restart: always
